before_build:
 - nuget restore
build_script:
 - msbuild /verbosity:quiet "Last.fm-Scrubbler-WPF.sln"
test_script:
 - Last.fm-Scrubbler-WPF-Test\TestCoverage\RunCoverage.bat
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile Last.fm-Scrubbler-WPF-Test\TestCoverage\codecov.sh
      bash Last.fm-Scrubbler-WPF-Test\TestCoverage\codecov.sh -f "coverage.xml" -t 69b3edab-2962-427c-9df8-71e0e1cd2132