image: Visual Studio 2017
before_build:
 - nuget restore
build_script:
 - msbuild /verbosity:quiet "Last.fm-Scrubbler-WPF.sln"
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"Last.fm-Scrubbler-WPF-Test\bin\Debug\Last.fm-Scrubbler-WPF-Test.exe" -output:".\coverage.xml" -filter:"+[Last.fm-Scrubbler-WPF]Scrubbler* -[Last.fm-Scrubbler-WPF]Scrubbler.Views.*"
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 69b3edab-2962-427c-9df8-71e0e1cd2132